CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id  BIGINT                      NOT NULL,
    author_id BIGINT                      NOT NULL,
    text      VARCHAR(7000)               NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE NOT NULL
);