server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**, /users/{userId}/events/{eventId}/requests/**

        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**, /users/{userId}/events/**, /events/**

        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**, /comments/**

        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: compilation_service_route
          uri: lb://compilation-service
          predicates:
            - Path=/admin/compilations/**, /compilations/**

        - id: category_service_route
          uri: lb://category-service
          predicates:
            - Path=/admin/categories/**, /categories/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway