spring:
  cloud:
    loadbalancer:
      configurations: health-check
      retry:
        enabled: true
    gateway:
      actuator.verbose.enabled: false
      discovery:
        locator:
          enabled: true
      routes:
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/categories/**, /admin/**, /users/**, /events/**, compilations/**
        - id: stats-service
          uri: lb://stats-server
          predicates:
            - Path=/stats/**, /hit/**

server:
  port: 8080